# Generated by Django 6.0.5 on 2026-07-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
